# Generated by Django 4.2.1 on 2023-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_adress_de_customuser_adress_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fp_token',
            field=models.CharField(max_length=110, null=True, unique=True),
        ),
    ]
