# Generated by Django 4.2.1 on 2023-05-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_work_objects_customuser_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='work_objects',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='work_type',
        ),
    ]
