# Generated by Django 4.2.1 on 2023-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vacations_days_quantity',
            field=models.CharField(max_length=2, null=True, verbose_name='Ilość przysługujących dni urlopu'),
        ),
    ]
