# Generated by Django 4.2.1 on 2023-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_vacations_days_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_year_vacations_days_quantity',
            field=models.IntegerField(null=True, verbose_name='Ilość przysługujących dni urlopu za zeszły rok'),
        ),
    ]
