# Generated by Django 4.2.1 on 2023-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_last_year_vacations_days_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_to_use_in_current_year',
            field=models.IntegerField(null=True, verbose_name='Do użycia w bieżącym roku'),
        ),
    ]
