# Generated by Django 4.2.1 on 2023-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_days_to_use_in_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_used_in_current_year',
            field=models.IntegerField(default=0, verbose_name='Użyto w bieżącym roku'),
        ),
    ]
