# Generated by Django 4.2.1 on 2023-06-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_days_used_in_current_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='days_used_in_current_year',
        ),
    ]
