# Generated by Django 4.2.1 on 2023-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_days_used_in_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cares_vacacions',
            field=models.IntegerField(default=16, verbose_name='Ilość godzin urlopu opiekuńczego'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vacacions_on_demand',
            field=models.IntegerField(default=4, verbose_name='Ilość dni urlopu na żądanie'),
        ),
    ]
