# Generated by Django 4.2.1 on 2023-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_cares_vacacions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_majeure_vacations',
            field=models.IntegerField(default=16, verbose_name='Ilość godzin urlopu z powodu siły wyższej'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cares_vacacions',
            field=models.IntegerField(default=5, verbose_name='Ilość godzin urlopu opiekuńczego'),
        ),
    ]
