# Generated by Django 4.2.1 on 2023-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_cares_vacacions_customuser_cares_vacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='compassionate_vacations',
            field=models.IntegerField(default=2, verbose_name='Ilość dni urlopu okolicznościowego'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cares_vacations',
            field=models.IntegerField(default=5, verbose_name='Ilość dni urlopu opiekuńczego'),
        ),
    ]
