# Generated by Django 4.2.1 on 2023-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_compassionate_vacations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_to_use_in_current_year_de',
            field=models.IntegerField(null=True, verbose_name='Do użycia w bieżącym roku de'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_year_vacations_days_quantity_de',
            field=models.IntegerField(null=True, verbose_name='Ilość przysługujących dni urlopu za zeszły rok de'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vacations_days_quantity_de',
            field=models.IntegerField(null=True, verbose_name='Ilość przysługujących dni urlopu de'),
        ),
    ]
