# Generated by Django 4.2.1 on 2023-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_days_to_use_in_current_year_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='days_to_use_in_current_year_de',
            field=models.IntegerField(null=True, verbose_name='Do użycia w bieżącym roku'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_year_vacations_days_quantity_de',
            field=models.IntegerField(null=True, verbose_name='Ilość przysługujących dni urlopu za zeszły rok'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacations_days_quantity_de',
            field=models.IntegerField(null=True, verbose_name='Ilość przysługujących dni urlopu'),
        ),
    ]
