# Generated by Django 4.2.1 on 2023-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_days_to_use_in_current_year_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
