# Generated by Django 4.2.1 on 2023-06-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unread_messages',
        ),
    ]
