# Generated by Django 4.2.1 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customuser_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='days_to_use_in_current_year',
            field=models.IntegerField(default=0, verbose_name='Do użycia w bieżącym roku'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='days_to_use_in_current_year_de',
            field=models.IntegerField(default=0, verbose_name='Do użycia w bieżącym roku'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_year_vacations_days_quantity',
            field=models.IntegerField(default=0, verbose_name='Ilość przysługujących dni urlopu za zeszły rok'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_year_vacations_days_quantity_de',
            field=models.IntegerField(default=0, verbose_name='Ilość przysługujących dni urlopu za zeszły rok'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacations_days_quantity',
            field=models.IntegerField(default=0, verbose_name='Ilość przysługujących dni urlopu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacations_days_quantity_de',
            field=models.IntegerField(default=0, verbose_name='Ilość przysługujących dni urlopu'),
        ),
    ]
