# Generated by Django 4.2.1 on 2023-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_customuser_days_to_use_in_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acceptation',
            field=models.BooleanField(default=False, verbose_name='Zatwierdź'),
        ),
    ]
