# Generated by Django 4.2.1 on 2023-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_acceptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas życia tokena'),
        ),
    ]
