# Generated by Django 4.2.1 on 2023-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_ipaddresslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddresslist',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
