# Generated by Django 4.2.1 on 2023-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_ipaddresslist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
