# Generated by Django 4.2.1 on 2023-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_customuser_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment',
            field=models.FloatField(null=True, verbose_name='Stawka za godzinę'),
        ),
    ]
