# Generated by Django 4.2.1 on 2023-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_customuser_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='administrator',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
    ]
