# Generated by Django 4.2.4 on 2023-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_customuser_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
