# Generated by Django 4.2.4 on 2023-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment',
            field=models.FloatField(default=0, null=True, verbose_name='Stawka za godzinę'),
        ),
    ]
