version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  django:
    container_name: AdestContainer
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      bash -c "python manage.py migrate &&
               gunicorn Adest.wsgi:application --bind 193.56.240.15:8000 --workers 3 --error-logfile ${GUNICORN_ERROR_LOGFILE}"
               
    volumes:
      - ./projects:/app/Adest
      - ./logs:/app
      - static:/home/user/django/static:ro  # Mount the STATIC_ROOT directory 
      - media:/home/user/django/media/:ro   # Mount the MEDIA_ROOT directory
    ports:
      - "193.56.240.15:8000:8000"
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - .env
    environment:   
      # - DOMAIN=domain.com       
      - LANG=pl_PL.UTF-8
      - LANGUAGE=pl_PL.UTF-8
      - LC_ALL=pl_PL.UTF-8
    hostname: django

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    hostname: celery
    command: celery -A Adest worker -l info --concurrency 1 --uid=nobody
    volumes:
      - ./projects:/app/Adest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    depends_on:
      - db
      - redis
  
  flower:
    build:
      context: .
    hostname: flower
    command: "celery -A Adest flower"
    volumes:
      - ./projects:/app/Adest
    depends_on:
      - redis
    ports:
    - "5555:5555"
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      # - "443:443"  # Expose port 443 for SSL
    volumes:
      # - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro #.d
      # - ./certs:/etc/nginx/certs:ro  # SSL certificates directory (read-only)

      # - ./static:/usr/share/nginx/html/static:ro  # Static files directory (read-only)
      - ./nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - static:/home/user/django/static:ro # Mount the STATIC_ROOT directory 
      - media:/home/user/django/media:ro  # Mount the MEDIA_ROOT directory
    depends_on:
      - django
  
volumes:
  dbdata:
  static:
  media: