version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  django:
    container_name: AdestContainer
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./projects:/app/Adest
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:          
      - LANG=pl_PL.UTF-8
      - LANGUAGE=pl_PL.UTF-8
      - LC_ALL=pl_PL.UTF-8
  
volumes:
  dbdata: