# Generated by Django 4.2.1 on 2023-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_work_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='coffee_food',
            field=models.IntegerField(null=True, verbose_name='Kawa/Posiłki'),
        ),
        migrations.AddField(
            model_name='work',
            name='fuel',
            field=models.IntegerField(null=True, verbose_name='Paliwo'),
        ),
        migrations.AddField(
            model_name='work',
            name='phone_costs',
            field=models.IntegerField(null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='work',
            name='prepayment',
            field=models.IntegerField(null=True, verbose_name='Zaliczka'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_object',
            field=models.CharField(max_length=100, null=True, verbose_name='Miejsce pracy'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Czynność'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(default='00-00-00', max_length=8, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='work',
            name='timefinish',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
        migrations.AlterField(
            model_name='work',
            name='timestart',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Początek'),
        ),
    ]
