# Generated by Django 4.2.1 on 2023-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_work_coffee_food_work_fuel_work_phone_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='coffee_food',
            field=models.FloatField(null=True, verbose_name='Kawa/Posiłki'),
        ),
        migrations.AlterField(
            model_name='work',
            name='fuel',
            field=models.FloatField(null=True, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='phone_costs',
            field=models.FloatField(null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='work',
            name='prepayment',
            field=models.FloatField(null=True, verbose_name='Zaliczka'),
        ),
    ]
