# Generated by Django 4.2.1 on 2023-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_work_coffee_food_alter_work_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='total_coffee_food',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
