# Generated by Django 4.2.1 on 2023-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_work_total_coffee_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='total_prepayment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
