# Generated by Django 4.2.1 on 2023-05-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_work_total_prepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='total_coffee_food',
        ),
        migrations.RemoveField(
            model_name='work',
            name='total_prepayment',
        ),
    ]
