# Generated by Django 4.2.1 on 2023-05-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_work_total_coffee_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='diff_time',
            field=models.FloatField(default=0.0, null=True, verbose_name='Czas pracy'),
        ),
    ]
