# Generated by Django 4.2.1 on 2023-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_work_diff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sum_time_sec',
            field=models.FloatField(default=0.0, null=True, verbose_name='Czas pracy razem'),
        ),
        migrations.AlterField(
            model_name='work',
            name='diff_time',
            field=models.CharField(default='00:00', max_length=5, null=True, verbose_name='Czas pracy'),
        ),
    ]
