# Generated by Django 4.2.1 on 2023-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_workobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_object',
        ),
        migrations.AddField(
            model_name='work',
            name='work_object',
            field=models.ManyToManyField(to='main.workobject'),
        ),
    ]
