# Generated by Django 4.2.1 on 2023-05-10 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_work_work_object_work_work_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
