# Generated by Django 4.2.1 on 2023-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_workobject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_object',
        ),
        migrations.AddField(
            model_name='work',
            name='work_object',
            field=models.CharField(max_length=100, null=True, verbose_name='Miejsce pracy'),
        ),
    ]
