# Generated by Django 4.2.1 on 2023-05-10 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_remove_workobject_user_remove_worktype_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workobject',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='workobject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
