# Generated by Django 4.2.1 on 2023-05-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_title_workobject_name_workobject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workobject',
            name='user',
        ),
    ]
