# Generated by Django 4.2.1 on 2023-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_workobject_user_workobject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_objects',
            field=models.ManyToManyField(to='main.workobject'),
        ),
    ]
