# Generated by Django 4.2.1 on 2023-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_work_work_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='coffee_food',
            field=models.CharField(default=0.0, max_length=100, null=True, verbose_name='Kawa/Posiłki'),
        ),
    ]
