# Generated by Django 4.2.1 on 2023-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_work_coffee_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='coffee_food',
            field=models.CharField(max_length=100, null=True, verbose_name='Kawa/Posiłki'),
        ),
        migrations.AlterField(
            model_name='work',
            name='fuel',
            field=models.CharField(max_length=100, null=True, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='phone_costs',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='work',
            name='prepayment',
            field=models.CharField(max_length=100, null=True, verbose_name='Zaliczka'),
        ),
    ]
