# Generated by Django 4.2.1 on 2023-05-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_work_sum_over_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='sum_over_time',
            new_name='sum_over_time_sec',
        ),
    ]
