# Generated by Django 4.2.1 on 2023-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_sum_over_time_work_sum_over_time_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalWorkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_coffee_food', models.CharField(max_length=100, null=True, verbose_name='Kawa/Posiłki')),
                ('obj_fuel', models.CharField(max_length=100, null=True, verbose_name='Paliwo')),
                ('obj_prepayment', models.CharField(max_length=100, null=True, verbose_name='Zaliczka')),
                ('obj_phone_costs', models.CharField(max_length=100, null=True, verbose_name='Telefon')),
                ('work_object', models.ManyToManyField(to='main.workobject')),
            ],
        ),
    ]
