# Generated by Django 4.2.1 on 2023-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_totalworkobject_obj_coffee_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalworkobject',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
