# Generated by Django 4.2.1 on 2023-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_workobject_coffee_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workobject',
            name='coffee_food',
            field=models.FloatField(default=0.0, null=True, verbose_name='Kawa/Posiłki'),
        ),
    ]
