# Generated by Django 4.2.1 on 2023-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_workobject_coffee_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='payment',
            field=models.CharField(default=0.0, max_length=100, null=True, verbose_name='Kwota'),
        ),
    ]
