# Generated by Django 4.2.1 on 2023-05-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_message_work_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
