# Generated by Django 4.2.1 on 2023-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
