# Generated by Django 4.2.1 on 2023-06-05 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
