# Generated by Django 4.2.1 on 2023-06-13 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0048_message_day_message_time_alter_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='Rok')),
                ('date', models.CharField(default='00-00-00', max_length=8, verbose_name='Data')),
                ('days_quantity', models.CharField(max_length=2, null=True, verbose_name='Ilość przysługujących dni')),
                ('days_to_use_in_current_year', models.CharField(max_length=2, null=True, verbose_name='Do użycia w bieżącym roku')),
                ('days_used_in_current_year', models.CharField(max_length=2, null=True, verbose_name='Użyto w bieżącym roku')),
                ('days_to_use_in_last_year', models.CharField(max_length=2, null=True, verbose_name='Do użycia w poprzednim roku')),
                ('days_used_in_last_year', models.CharField(max_length=2, null=True, verbose_name='Użyto w poprzednim roku')),
                ('days_planned', models.CharField(max_length=2, null=True, verbose_name='Zaplanowany urlop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
