# Generated by Django 4.2.1 on 2023-06-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_vacations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='days_quantity',
        ),
    ]
