# Generated by Django 4.2.1 on 2023-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_vacations_days_to_use_in_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='days_to_use_in_current_year',
            field=models.CharField(max_length=2, null=True, verbose_name='Do użycia w bieżącym roku'),
        ),
    ]
