# Generated by Django 4.2.1 on 2023-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_vacations_days_to_use_in_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='date',
            field=models.CharField(default='00-00-0000', max_length=10, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='year',
            field=models.CharField(default='0000', max_length=4, verbose_name='Rok'),
        ),
    ]
