# Generated by Django 4.2.1 on 2023-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_vacations_date_alter_vacations_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Typ urlopu'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='v_from',
            field=models.CharField(default='00-00-0000', max_length=10, verbose_name='Od'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='v_to',
            field=models.CharField(default='00-00-0000', max_length=10, verbose_name='Do'),
        ),
    ]
