# Generated by Django 4.2.1 on 2023-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_vacations_type_vacations_v_from_vacations_v_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Akceptacja'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='consideration',
            field=models.BooleanField(default=False, verbose_name='Rozpatrywanie'),
        ),
    ]
