# Generated by Django 4.2.1 on 2023-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_vacations_days_planned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='days_planned',
            field=models.IntegerField(null=True, verbose_name='Zaplanowany urlop'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='days_to_use_in_current_year',
            field=models.IntegerField(null=True, verbose_name='Do użycia w bieżącym roku'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='days_to_use_in_last_year',
            field=models.IntegerField(null=True, verbose_name='Do użycia w poprzednim roku'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='days_used_in_current_year',
            field=models.IntegerField(default=0, verbose_name='Użyto w bieżącym roku'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='days_used_in_last_year',
            field=models.IntegerField(default=0, verbose_name='Użyto w poprzednim roku'),
        ),
    ]
