# Generated by Django 4.2.1 on 2023-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_vacations_days_planned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='actually_days_to_use',
            field=models.IntegerField(default=0, verbose_name='Faktyczny urlop według przepracowanych dni'),
        ),
    ]
