# Generated by Django 4.2.1 on 2023-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_vacations_actually_days_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='days_to_use_in_last_year',
            field=models.IntegerField(default=0, verbose_name='Do użycia w poprzednim roku'),
        ),
    ]
