# Generated by Django 4.2.1 on 2023-06-14 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0063_alter_vacations_days_to_use_in_last_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationDaysQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_use_in_current_year', models.IntegerField(null=True, verbose_name='Do użycia w bieżącym roku')),
                ('days_used_in_current_year', models.IntegerField(default=0, verbose_name='Użyto w bieżącym roku')),
                ('days_to_use_in_last_year', models.IntegerField(default=0, verbose_name='Do użycia w poprzednim roku')),
                ('days_used_in_last_year', models.IntegerField(default=0, verbose_name='Użyto w poprzednim roku')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
