# Generated by Django 4.2.1 on 2023-06-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_vacationdaysquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='days_to_use_in_current_year',
        ),
    ]
