# Generated by Django 4.2.1 on 2023-06-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_vacations_days_to_use_in_last_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacationDaysQuantity',
        ),
    ]
