# Generated by Django 4.2.1 on 2023-06-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='for_recipient_is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='for_sender_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
