# Generated by Django 4.2.1 on 2023-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_rename_is_read_message_for_recipient_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.TextField(null=True),
        ),
    ]
