# Generated by Django 4.2.1 on 2023-06-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_isread_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isread',
            name='work_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workobject'),
        ),
    ]
