# Generated by Django 4.2.1 on 2023-07-03 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0078_work_username_alter_isread_work_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nadawca', to=settings.AUTH_USER_MODEL),
        ),
    ]
