# Generated by Django 4.2.1 on 2023-07-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0086_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=250, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=15, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Wykonano'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wyconawca', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='main.workobject', verbose_name='Objekt'),
        ),
    ]
