# Generated by Django 4.2.1 on 2023-07-07 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_alter_task_content_alter_task_date_alter_task_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_obj',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
