# Generated by Django 4.2.1 on 2023-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_task_date_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='Treść'),
        ),
    ]
