# Generated by Django 4.2.1 on 2023-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_vacations_username_alter_vacations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Imię użytkownika'),
        ),
    ]
