# Generated by Django 4.2.1 on 2023-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_vacations_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='abbreviated_month',
            field=models.CharField(max_length=5, null=True, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='work',
            name='coffee_food',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kawa/Posiłki'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(default='00-00-00', max_length=20, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='work',
            name='fuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='work',
            name='phone_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='work',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Zaliczka'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sum_over_time_sec',
            field=models.FloatField(default=0.0, null=True, verbose_name='Nadgodziny'),
        ),
    ]
