# Generated by Django 4.2.1 on 2023-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_task_abbreviated_month_alter_work_coffee_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
