# Generated by Django 4.2.1 on 2023-08-12 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0093_workobject_message_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workobject')),
            ],
        ),
    ]
