# Generated by Django 4.2.1 on 2023-08-13 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_messagecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='date_obj',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='work_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekt', to='main.workobject'),
        ),
    ]
