# Generated by Django 4.2.1 on 2023-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_workobject_date_obj_alter_message_work_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workobject',
            name='date_obj',
        ),
        migrations.AddField(
            model_name='workobject',
            name='timefinish',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='timestart',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Początek'),
        ),
    ]
