# Generated by Django 4.2.1 on 2023-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_workobject_date_obj_workobject_timefinish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workobject',
            name='timefinish',
            field=models.CharField(default='00:00', max_length=25, verbose_name='Koniec'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='timestart',
            field=models.CharField(default='00:00', max_length=25, verbose_name='Początek'),
        ),
    ]
