# Generated by Django 4.2.1 on 2023-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_alter_workobject_timefinish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workobject',
            name='message_count',
        ),
        migrations.AddField(
            model_name='workobject',
            name='status',
            field=models.CharField(default='Aktywne', max_length=150),
        ),
    ]
