# Generated by Django 4.2.1 on 2023-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_remove_workobject_message_count_workobject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workobject',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
