# Generated by Django 4.2.1 on 2023-08-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_documents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='timefinish_break1',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
        migrations.AddField(
            model_name='work',
            name='timefinish_break2',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
        migrations.AddField(
            model_name='work',
            name='timestart_break1',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
        migrations.AddField(
            model_name='work',
            name='timestart_break2',
            field=models.CharField(default='00:00', max_length=5, verbose_name='Koniec'),
        ),
    ]
