# Generated by Django 4.2.4 on 2023-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_messagecountuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('column', models.CharField(max_length=100)),
            ],
        ),
    ]
