# Generated by Django 4.2.4 on 2023-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='column',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='level',
        ),
    ]
