# Generated by Django 4.2.4 on 2023-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_warehouse_is_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='workobject',
            name='days_difference',
            field=models.IntegerField(default=0, verbose_name='Pozostały czas'),
        ),
    ]
